version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  node-app:
    restart: on-failure
    build: ./app
    ports:
      - "8000:8080"
  nginx:
    build: ./nginx
    ports:
      - "85:80"
    depends_on:
      - node-app